### PR TITLE
Adding Set to Groupcache

### PR DESCRIPTION
**Pull request by rneillj**

### CODE REVIEW

**Comment by tdterry** [comment]
Hi. I've been looking at groupcache recently, and one of the things holding me back was the inability to `Set` a value. I was just considering how to write it when I found this PR. I think I've found a couple of issues. Do you mind a constructive PR review from someone who's not involved in the project?

**Comment by thrawn01** [comment]
@tdterry please do! This first implementation seems trivial, we were just discussing how we go about proving this works in practice.

**Comment by develar** [comment]
Why it is not yet merged? Not tested changes?

**Comment by awartoft** [comment]
This would solve the ticket that I recently opened (#34) what needs to be done for this to be merged? 

Happy to help out

**Comment by thrawn01** [comment]
This feature is working in production, merging and releasing.

**Pull request merged**
